In [1]:
import pandas as pd
from datetime import datetime
import calendar
import numpy as np
from generate_preprocessed_data import *

In [12]:
raw_df = pd.read_csv(DATA_ROOTFOLDER / "NODE.csv")
df = raw_df
raw_df

,ACCIDENT_NO,NODE_ID,NODE_TYPE,VICGRID94_X,VICGRID94_Y,LGA_NAME,LGA_NAME_ALL,REGION_NAME,DEG_URBAN_NAME,Lat,Long,POSTCODE_NO
0,T20060002689,22,I,2495701.925,2411599.135,MELBOURNE,MELBOURNE,METROPOLITAN NORTH WEST REGION,MELB_URBAN,-37.796596,144.951197,3051
1,T20060010827,22,I,2495701.925,2411599.135,MELBOURNE,MELBOURNE,METROPOLITAN NORTH WEST REGION,MELB_URBAN,-37.796596,144.951197,3051
2,T20060017279,22,I,2495701.925,2411599.135,MELBOURNE,MELBOURNE,METROPOLITAN NORTH WEST REGION,MELB_URBAN,-37.796596,144.951197,3051
3,T20060041762,22,I,2495701.925,2411599.135,MELBOURNE,MELBOURNE,METROPOLITAN NORTH WEST REGION,MELB_URBAN,-37.796596,144.951197,3051
4,T20060047478,22,I,2495701.925,2411599.135,MELBOURNE,MELBOURNE,METROPOLITAN NORTH WEST REGION,MELB_URBAN,-37.796596,144.951197,3051
...,...,...,...,...,...,...,...,...,...,...,...,...
221792,T20090046106,229103,N,2499211.462,2428380.388,WHITTLESEA,WHITTLESEA,METROPOLITAN NORTH WEST REGION,MELB_URBAN,-37.645401,144.991064,3076
221793,T20090046106,229103,N,2499211.462,2428380.388,WHITTLESEA,WHITTLESEA,METROPOLITAN NORTH WEST REGION,RURAL_VICTORIA,-37.645401,144.991064,3076
221794,T20090047746,229114,N,2508240.178,2412119.954,BOROONDARA,BOROONDARA,METROPOLITAN SOUTH EAST REGION,MELB_URBAN,-37.791877,145.093559,3104
221795,T20090044445,229087,N,2653269.886,2599283.209,INDIGO,INDIGO,NORTH EASTERN REGION,RURAL_VICTORIA,-36.092861,146.702041,3688
221796,T20090046194,229105,N,2592208.478,2362963.486,BAW BAW,BAW BAW,EASTERN REGION,RURAL_VICTORIA,-38.230181,146.053062,3823

### Granularity :
 Thanks to the following cells we deduce the granularity of the raw table : ["ACCIDENT_NO", "POSTCODE_NO","DEG_URBAN_NAME"]

In [9]:
len(df[df[["ACCIDENT_NO"]].duplicated(keep=False)].sort_values(by="ACCIDENT_NO"))

36201

In [10]:
len(df[df[["ACCIDENT_NO", "POSTCODE_NO"]].duplicated(keep=False)].sort_values(by="ACCIDENT_NO").head())

5

In [11]:
len(df[df[["ACCIDENT_NO", "POSTCODE_NO","DEG_URBAN_NAME"]].duplicated(keep=False)].sort_values(by="ACCIDENT_NO"))

0

But considering the number and the nature (why an accident would be located at several post codes?) it seemed to be that it was corrupted data and I decided not to take those duplicates in order to keep having an ACCIDENT_NO granularity

In [14]:
df = df[~df["ACCIDENT_NO"].duplicated(keep=False)]

In [15]:
discarded_columns = ["VICGRID94_X","VICGRID94_Y", "LGA_NAME_ALL", "POSTCODE_NO", "NODE_TYPE"] 
df = df.drop(columns = discarded_columns).set_index("ACCIDENT_NO", verify_integrity= True)
df

,NODE_ID,LGA_NAME,REGION_NAME,DEG_URBAN_NAME,Lat,Long
ACCIDENT_NO,,,,,,
T20060017759,83,MELBOURNE,METROPOLITAN NORTH WEST REGION,MELB_URBAN,-37.804039,144.958469
T20060041501,83,MELBOURNE,METROPOLITAN NORTH WEST REGION,MELB_URBAN,-37.804039,144.958469
T20060038415,83,MELBOURNE,METROPOLITAN NORTH WEST REGION,MELB_URBAN,-37.804039,144.958469
T20060039466,83,MELBOURNE,METROPOLITAN NORTH WEST REGION,MELB_URBAN,-37.804039,144.958469
T20070005482,83,MELBOURNE,METROPOLITAN NORTH WEST REGION,MELB_URBAN,-37.804039,144.958469
...,...,...,...,...,...,...
T20090043852,229064,ALPINE,NORTH EASTERN REGION,TOWNS,-36.564190,146.726171
T20090046284,229107,WHITTLESEA,METROPOLITAN NORTH WEST REGION,MELB_URBAN,-37.676468,145.050491
T20090047746,229114,BOROONDARA,METROPOLITAN SOUTH EAST REGION,MELB_URBAN,-37.791877,145.093559
T20090044445,229087,INDIGO,NORTH EASTERN REGION,RURAL_VICTORIA,-36.092861,146.702041
T20090046194,229105,BAW BAW,EASTERN REGION,RURAL_VICTORIA,-38.230181,146.053062